name: 'Get and Cache dependecies'
description: 'Get the dependecies via npm and cache them.'
inputs:
  caching:
    description: 'Wether to cache dependecies or not.'
    required: false
    default: 'true'
outputs:
  uses-cache:
    description: 'Wether cache was used.'
    value: ${{ steps.install.outputs.uses-cache }}
runs:
  using: 'composite'
  steps: 
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "uses-cache=${{ inputs.caching }}" >> "$GITHUB_OUTPUT"
      shell: bash